In [71]:
# Sekcja 1
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [77]:
# Sekcja 2
np.random.seed(42)

In [78]:
# Sekcja 3
df = pd.DataFrame({"wiek": np.random.randint(18, 65, 100), "wzrost": np.random.randint(150, 190, 100), "waga": np.random.randint(50, 90, 100)})

In [79]:
# Sekcja 4
df.info()
display(df.describe())
display(df.head())

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   wiek    100 non-null    int32
 1   wzrost  100 non-null    int32
 2   waga    100 non-null    int32
dtypes: int32(3)
memory usage: 1.3 KB

            wiek      wzrost        waga
count  100.00000  100.000000  100.000000
mean    40.88000  170.560000   70.360000
std     13.99082   12.590938   11.717655
min     18.00000  150.000000   50.000000
25%     30.50000  158.000000   60.000000
50%     41.00000  173.000000   70.500000
75%     53.25000  182.000000   81.250000
max     64.00000  189.000000   89.000000

   wiek  wzrost  waga
0    56     157    75
1    46     173    81
2    32     160    55
3    60     166    81
4    25     157    53